name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
        flags: [ "", "DEBUG=1", "GDB=1", "CLI=1", "DIFF=1", "PERF=1" ]
        cores: [ "la464", "centaur320" ]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq clang

    - name: Build with ${{ matrix.compiler }}, flags is ${{ matrix.flags }}, core is ${{ matrix.cores }}
      run: |
        make clean
        make -j$(nproc) CC=${{ matrix.compiler }} ${{ matrix.flags }} CORE=${{ matrix.cores }}